#!/bin/bash

_docker_enter()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=`docker ps --format "{{.Names}}" --filter status=running`

    COMPREPLY=( $( compgen -W "${opts}" -- "$cur" ) )
}

complete -F _docker_enter docker-enter

# ex: ts=4 sw=4 et filetype=sh
